void output_str_1(int,int);
void output_str_2(int number,char name[25],char cost1[4],char cost2[4]);
int input_str_2(void);
void logo(void);
int gui(void);
void gui_chouse_cat(void);
void endlist(void);
void gui_chouse_sel(void);
void endoutputlist(void);
void topaddlist(void);
void topseelist(void);
void topdellist(void);
void topsearchlist(void);
char input_str_3(void);
void endoutputlist1(void);
void endoutputlist2(void);
void printCat(void);
void warningNoNom(void);
